spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8090/auth/realms/pp"  
  data:
    mongodb:
      database: manage-data
      host: localhost
      port: 27017
  rabbitmq:
      password: JMF_D6eSRwN_cAZr8uzC1eIfiboEAkcp
      addresses: amqps://zxzhkovo:JMF_D6eSRwN_cAZr8uzC1eIfiboEAkcp@puffin.rmq2.cloudamqp.com/zxzhkovo
      username: zxzhkovo
keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: Pp
  public-client: 'true'
  resource: pp
  ssl-required: external     
  principal-attribute: preferred_username
     

server:
  port:
    9005

manage-service:
  exceptions:
    market-not-found: Market not found or not exists please check.
    
    

