spring:
  data:
    mongodb:
      database: manage-data
      host: localhost
      port: 27017
  rabbitmq:
      password: JMF_D6eSRwN_cAZr8uzC1eIfiboEAkcp
      addresses: amqps://zxzhkovo:JMF_D6eSRwN_cAZr8uzC1eIfiboEAkcp@puffin.rmq2.cloudamqp.com/zxzhkovo
      username: zxzhkovo
      
          
      

server:
  port:
    9005


